-- Migration: Criar primeiro usuário admin (opcional)
-- Descrição: Script para criar manualmente o primeiro usuário admin
-- IMPORTANTE: Este script deve ser executado manualmente após criar o primeiro usuário no auth.users
-- 
-- Passos:
-- 1. Criar usuário no Supabase Auth (via dashboard ou SQL)
-- 2. Executar este script substituindo os valores entre <>
--
-- Exemplo de criação de usuário no auth.users:
-- INSERT INTO auth.users (
--   instance_id,
--   id,
--   aud,
--   role,
--   email,
--   encrypted_password,
--   email_confirmed_at,
--   created_at,
--   updated_at,
--   confirmation_token,
--   email_change,
--   email_change_token_new,
--   recovery_token
-- ) VALUES (
--   '00000000-0000-0000-0000-000000000000',
--   gen_random_uuid(),
--   'authenticated',
--   'authenticated',
--   'admin@exemplo.com',
--   crypt('senha_segura_aqui', gen_salt('bf')),
--   NOW(),
--   NOW(),
--   NOW(),
--   '',
--   '',
--   '',
--   ''
-- );
--
-- Depois, inserir na tabela usuarios:
-- INSERT INTO public.usuarios (id, nome, email, permissao, ativo)
-- SELECT id, 'Administrador', email, 'admin', true
-- FROM auth.users
-- WHERE email = 'admin@exemplo.com'
-- ON CONFLICT (id) DO NOTHING;

-- Este arquivo serve apenas como documentação
-- A criação do primeiro admin deve ser feita manualmente via dashboard do Supabase
-- ou através de uma Edge Function temporária

COMMENT ON TABLE public.usuarios IS 'Para criar o primeiro admin: 1) Criar usuário no Auth, 2) Inserir registro na tabela usuarios com permissao=admin';

